
##### Checks run at pull request #####
# Check that urls in the content are not broken
url-checker: yes
# Render preview of content with changes (Rmd's and md's are checked)
render-preview: yes
# Spell check Rmds and quizzes
spell-check: yes

##### Renderings run upon merge to main branch #####
render-markdown: yes

# What docker image should be used for rendering?
rendering-docker-image: 'jhudsl/bcds_toolbank_2023:1.1'
