---
title: "Data Cleaning for ToolBank Project"
---

```{r, echo = FALSE, include=FALSE, purl=FALSE}
library(knitr)
opts_chunk$set(comment = "")
```

```{r, include=FALSE}
library(tidyverse)
library(googlesheets4)
```

```{r eval=FALSE}
# Prompts a browser pop-up
gs4_auth()
```
```{r}
# Once set up, you can automate this process by passing your email
gs4_auth(email = "karinchen737@gmail.com")
```

## Reading data with the googlesheets4 package {.smaller}

```{r}
sheet_url <- 
  "https://docs.google.com/spreadsheets/d/1W5kgOFSJux4lqpwqwJ_h9tJnd5oTY3-wBs57cpkyM3U/edit#gid=1386397630"
sheet_dat_1 <- read_sheet(sheet_url)
head(sheet_dat_1)
```

## Delete extra variables
```{r}
# delete Noah's test response
# also delete the "Please specify:" question after receiving the first response, so we want to delete the corresponding column
data = sheet_dat_1[sheet_dat_1$`di_org_Name of your current organization` != "Baltimore ToolBank", 
                   !names(sheet_dat_1) %in% c("Please specify:")]
head(data)
```

## change column names to variables
```{r}
varlist = c("timestamp","di_org", "di_orgyearsworked", "di_mled", "att_purtool", "att_strtool", "att_redtime", "att_evquality", "att_posimpact", "att_mostimpact", "eco_purchase", "eco_storage", "eco_maintain", "eco_totalcost", "eco_events", "eco_nothost", "eco_constit", "ci_exaccomp", "ci_cutfund", "ci_otr", "ci_staff", "ci_project", "ci_evimpact", "eve_type", "eve_fundraise", "eve_fundraise_p")

colnames(data) = varlist
str(data)
```

## change multiple choice answer into numbers
```{r}
# Question: how long have you worked with this organization
# variable: di_orgyearsworked; choice: 1 - 0-2 years; 2 - 3-5 years; 3 - More than 5 years

data$di_orgyearsworked = ifelse(data$di_orgyearsworked == "0-2 years", 1,
                                ifelse(data$di_orgyearsworked == "3-5 years", 2, 3))
head(data)
```

```{r}
# Question: general attitudes
# variables: "att_purtool", "att_strtool", "att_redtime", "att_evquality", "att_posimpact"
# 1 - Strongly agree; 2 - Agree; 3 - Neutral; 4 - Disagree; 5 - Strongly disagree; 6 - N/A
att_mc = c("att_purtool", "att_strtool", "att_redtime", "att_evquality", "att_posimpact")

invisible(lapply(att_mc, FUN = function(x) {
  data[[x]] <<- ifelse(data[[x]] == "Strongly agree", 1,
                     ifelse(data[[x]] == "Agree", 2,
                            ifelse(data[[x]] == "Neutral", 3,
                                   ifelse(data[[x]] == "Disagree", 4,
                                          ifelse(data[[x]] == "Strongly disagree", 5, 6)))))
}))

head(data)
```

## split check all that apply responses into indicators
```{r}
# Question 1: minority leadership
data = mutate(data, di_mled_top = NA, di_mled_board = NA, di_mled_rep = NA, di_mled_na = NA)

invisible(lapply(1:nrow(data), FUN = function(x) {
  choicelist = strsplit(data$di_mled[x], ", ")[[1]]
  if ("Our top executive position is held by a minority." %in% choicelist) {
    data$di_mled_top[x] <<- 1
  } else { 
    data$di_mled_top[x] <<- 0
  }
  
  if ("More than 50% of our board is made up of minorities." %in% choicelist) {
    data$di_mled_board[x] <<- 1
  } else { 
    data$di_mled_board[x] <<- 0
  }
  
  if ("More than 50% of program recipients are minorities." %in% choicelist) {
    data$di_mled_rep[x] <<- 1
  } else { 
    data$di_mled_rep[x] <<- 0
  }
  
  if ("None of the above" %in% choicelist) {
    data$di_mled_na[x] <<- 1
  } else { 
    data$di_mled_na[x] <<- 0
  }
}))

head(data)
```

```{r}
# Question 2: With the money you have saved on purchasing, storing, and maintaining tools and equipment through the TB, what have you been able to accomplish?
data = mutate(data, ci_exaccomp_stf = NA, ci_exaccomp_prj = NA, ci_exaccomp_na = NA, ci_exaccomp_otr = NA)

invisible(lapply(1:nrow(data), FUN = function(x) {
  choicelist = strsplit(data$ci_exaccomp[x], ", ")[[1]]
  if ("Hired additional staff positions" %in% choicelist) {
    data$ci_exaccomp_stf[x] <<- 1
  } else { 
    data$ci_exaccomp_stf[x] <<- 0
  }
  
  choicelist = choicelist[choicelist != "Hired additional staff positions"]
  
  if ("Hosted additional projects or events" %in% choicelist) {
    data$ci_exaccomp_prj[x] <<- 1
  } else { 
    data$ci_exaccomp_prj[x] <<- 0
  }
  
  choicelist = choicelist[choicelist != "Hosted additional projects or events"]
  
  
  if ("N/A" %in% choicelist) {
    data$ci_exaccomp_na[x] <<- 1
  } else { 
    data$ci_exaccomp_na[x] <<- 0
  }
  
  choicelist = choicelist[choicelist != "N/A"]
  
  if (length(choicelist > 0)) {
    print(x)
    data$ci_exaccomp_otr[x] <<- paste(choicelist, collapse = ", ")
  }
}))

head(data)
```

```{r}
# Question 3: Without the TB, what would you no longer be able to fund?
data = mutate(data, ci_cutfund_stf = NA, ci_cutfund_prj = NA, ci_cutfund_na = NA, ci_cutfund_otr = NA)

invisible(lapply(1:nrow(data), FUN = function(x) {
  choicelist = strsplit(data$ci_cutfund[x], ", ")[[1]]
  if ("Staff" %in% choicelist) {
    data$ci_cutfund_stf[x] <<- 1
  } else { 
    data$ci_cutfund_stf[x] <<- 0
  }
  
  choicelist = choicelist[choicelist != "Staff"]
  
  if ("Projects" %in% choicelist) {
    data$ci_cutfund_prj[x] <<- 1
  } else { 
    data$ci_cutfund_prj[x] <<- 0
  }
  
  choicelist = choicelist[choicelist != "Projects"]
  
  
  if ("N/A" %in% choicelist) {
    data$ci_cutfund_na[x] <<- 1
  } else { 
    data$ci_cutfund_na[x] <<- 0
  }
  
  choicelist = choicelist[choicelist != "N/A"]
  
  if (length(choicelist > 0)) {
    print(x)
    data$ci_cutfund_otr[x] <<- paste(choicelist, collapse = ", ")
  }
}))

head(data)
```

```{r}
# Question 4: Without the TB, which of the following are ways that your community events would be impacted? (check all that apply)
data = mutate(data, ci_evimpact_qtt = NA, ci_evimpact_qlt = NA, ci_evimpact_dvt = NA, 
              ci_evimpact_cst = NA, ci_evimpact_otr = NA)

invisible(lapply(1:nrow(data), FUN = function(x) {
  choicelist = strsplit(data$ci_evimpact[x], ", ")[[1]]
  if ("Quantity" %in% choicelist) {
    data$ci_evimpact_qtt[x] <<- 1
  } else { 
    data$ci_evimpact_qtt[x] <<- 0
  }
  
  choicelist = choicelist[choicelist != "Quantity"]
  
  if ("Quality" %in% choicelist) {
    data$ci_evimpact_qlt[x] <<- 1
  } else { 
    data$ci_evimpact_qlt[x] <<- 0
  }
  
  choicelist = choicelist[choicelist != "Quality"]
  
  
  if ("Diversity" %in% choicelist) {
    data$ci_evimpact_dvt[x] <<- 1
  } else { 
    data$ci_evimpact_dvt[x] <<- 0
  }
  
  choicelist = choicelist[choicelist != "Diversity"]
  
  if ("Consistency" %in% choicelist) {
    data$ci_evimpact_cst[x] <<- 1
  } else { 
    data$ci_evimpact_cst[x] <<- 0
  }
  
  choicelist = choicelist[choicelist != "Consistency"]
  
  if (length(choicelist > 0)) {
    print(x)
    data$ci_evimpact_otr[x] <<- paste(choicelist, collapse = ", ")
  }
}))

head(data)
```

```{r}
# Question 5: Which of the following types of events have TB tools and equipment helped your CBO complete?
data = mutate(data, eve_type_fr = NA, eve_type_sp = NA, eve_type_ew = NA, eve_type_cb = NA, eve_type_otr = NA)

invisible(lapply(1:nrow(data), FUN = function(x) {
  choicelist = strsplit(data$eve_type[x], ", ")[[1]]
  if ("Fundraising" %in% choicelist) {
    data$eve_type_fr[x] <<- 1
  } else { 
    data$eve_type_fr[x] <<- 0
  }
  
  choicelist = choicelist[choicelist != "Fundraising"]
  
  if ("Service Projects" %in% choicelist) {
    data$eve_type_sp[x] <<- 1
  } else { 
    data$eve_type_sp[x] <<- 0
  }
  
  choicelist = choicelist[choicelist != "Service Projects"]
  
  
  if ("Educational Workshops" %in% choicelist) {
    data$eve_type_ew[x] <<- 1
  } else { 
    data$eve_type_ew[x] <<- 0
  }
  
  choicelist = choicelist[choicelist != "Educational Workshops"]
  
  if ("Community Building" %in% choicelist) {
    data$eve_type_cb[x] <<- 1
  } else { 
    data$eve_type_cb[x] <<- 0
  }
  
  choicelist = choicelist[choicelist != "Community Building"]
  
  if (length(choicelist > 0)) {
    print(x)
    data$eve_type_otr[x] <<- paste(choicelist, collapse = ", ")
  }
}))

head(data)
```

