
##### Checks run at pull request #####
# Render preview of content with changes (Rmd's and md's are checked)
render-preview: yes

##### Renderings run upon merge to main branch #####
render-markdown: yes

# What docker image should be used for rendering?
rendering-docker-image: 'jhudsl/bcds_toolbank_2023:1.1'
